"""f-divergences (phi-divergences) between discrete probability distributions."""

from collections.abc import Callable

import torch

from optora.core.divergence_base import Divergence


def _chi_square_generator(ratio: torch.Tensor) -> torch.Tensor:
    """Convex generator `phi(t) = (t - 1)^2` for the chi-square divergence.

    Args:
        ratio: Elementwise density ratio `p / q`.

    Returns:
        `phi` evaluated elementwise on `ratio`.
    """
    return (ratio - 1.0) ** 2


def _total_variation_generator(ratio: torch.Tensor) -> torch.Tensor:
    """Convex generator `phi(t) = |t - 1| / 2` for the total variation divergence.

    Args:
        ratio: Elementwise density ratio `p / q`.

    Returns:
        `phi` evaluated elementwise on `ratio`.
    """
    return 0.5 * torch.abs(ratio - 1.0)


class PhiDivergence(Divergence):
    r"""General f-divergence generated by a caller-supplied convex function.

    For discrete distributions represented as nonnegative tensors that sum to
    one along their last dimension, computes
    `D_phi(p || q) = sum_i q_i * phi(p_i / q_i)` for a convex generator `phi`
    with `phi(1) = 0`. `ChiSquareDivergence` and `TotalVariationDivergence`
    are `PhiDivergence` instances with a fixed generator; researchers can
    subclass or instantiate `PhiDivergence` directly with any other convex
    generator to define further phi-divergence-based ambiguity sets in
    `optora.dro.phi_dro`.

    Attributes:
        phi: Convex generator function with `phi(1) = 0`, applied elementwise
            to the density ratio `p / q`.
        eps: Small positive constant used to clamp `q` away from zero before
            dividing, avoiding division by zero without branching.
    """

    def __init__(
        self, phi: Callable[[torch.Tensor], torch.Tensor], eps: float = 1e-12
    ) -> None:
        """Initialize the phi-divergence.

        Args:
            phi: Convex generator function with `phi(1) = 0`, applied
                elementwise to the density ratio `p / q`.
            eps: Small positive constant used to clamp `q` away from zero
                before dividing.

        Raises:
            ValueError: If `eps` is not positive.
        """
        super().__init__()
        if eps <= 0:
            raise ValueError(f"eps must be positive, got {eps}.")
        self.phi = phi
        self.eps = eps

    def forward(self, p: torch.Tensor, q: torch.Tensor) -> torch.Tensor:
        """Compute the phi-divergence of `p` from `q`.

        Args:
            p: Candidate distribution, a nonnegative tensor that sums to one
                along its last dimension.
            q: Reference distribution with the same shape as `p`.

        Returns:
            A scalar tensor holding `D_phi(p || q)`, clamped to be
            nonnegative to absorb floating-point error near zero.
        """
        q_safe = torch.clamp(q, min=self.eps)
        ratio = p / q_safe
        divergence = torch.sum(q_safe * self.phi(ratio))
        return torch.clamp(divergence, min=0.0)


class ChiSquareDivergence(PhiDivergence):
    r"""Chi-square divergence of a candidate distribution from a reference.

    Computes `D_chi2(p || q) = sum_i (p_i - q_i)^2 / q_i`, the phi-divergence
    generated by `phi(t) = (t - 1)^2`. `optora.dro.phi_dro` uses this
    divergence to define chi-square ambiguity sets.
    """

    def __init__(self, eps: float = 1e-12) -> None:
        """Initialize the chi-square divergence.

        Args:
            eps: Small positive constant used to clamp `q` away from zero
                before dividing.

        Raises:
            ValueError: If `eps` is not positive.
        """
        super().__init__(phi=_chi_square_generator, eps=eps)

    def forward(self, p: torch.Tensor, q: torch.Tensor) -> torch.Tensor:
        """Compute the chi-square divergence of `p` from `q`.

        Uses the closed form `(p - q)^2 / q` directly instead of routing
        through `PhiDivergence`'s generic `q * phi(p / q)` path: `q * (p / q
        - 1)^2` and `(p - q)^2 / q` are algebraically identical, but the
        generic path divides by `q` and then multiplies by `q` again after
        squaring, a round trip that costs an extra elementwise operation and
        loses precision by squaring an already-divided ratio before
        rescaling it back up.

        Args:
            p: Candidate distribution, a nonnegative tensor that sums to one
                along its last dimension.
            q: Reference distribution with the same shape as `p`.

        Returns:
            A scalar tensor holding `D_chi2(p || q)`, clamped to be
            nonnegative to absorb floating-point error near zero.
        """
        q_safe = torch.clamp(q, min=self.eps)
        divergence = torch.sum((p - q_safe) ** 2 / q_safe)
        return torch.clamp(divergence, min=0.0)


class TotalVariationDivergence(PhiDivergence):
    r"""Total variation divergence of a candidate distribution from a reference.

    Computes `D_TV(p || q) = 0.5 * sum_i |p_i - q_i|`, the phi-divergence
    generated by `phi(t) = |t - 1| / 2`. `optora.dro.phi_dro` uses this
    divergence to define total-variation ambiguity sets.
    """

    def __init__(self, eps: float = 1e-12) -> None:
        """Initialize the total variation divergence.

        Args:
            eps: Small positive constant used to clamp `q` away from zero
                before dividing.

        Raises:
            ValueError: If `eps` is not positive.
        """
        super().__init__(phi=_total_variation_generator, eps=eps)

    def forward(self, p: torch.Tensor, q: torch.Tensor) -> torch.Tensor:
        """Compute the total variation divergence of `p` from `q`.

        Uses the closed form `0.5 * sum(|p - q|)` directly instead of
        routing through `PhiDivergence`'s generic `q * phi(p / q)` path:
        for `q > 0`, `q * |p / q - 1| = |p - q|`, so the `q` factor and the
        division it required cancel out algebraically. This removes the
        division (and its `eps` clamp) from the computation entirely rather
        than merely guarding it.

        Args:
            p: Candidate distribution, a nonnegative tensor that sums to one
                along its last dimension.
            q: Reference distribution with the same shape as `p`.

        Returns:
            A scalar tensor holding `D_TV(p || q)`, clamped to be
            nonnegative to absorb floating-point error near zero.
        """
        divergence = 0.5 * torch.sum(torch.abs(p - q))
        return torch.clamp(divergence, min=0.0)
