"""Generate and run the Optora documentation site."""

from __future__ import annotations

import argparse
import ast
import re
import subprocess
import sys
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path

GENERATED_NOTICE = "<!-- Generated by tools.docs; do not edit manually. -->"
DISPLAY_NAMES = {
    "dro": "DRO",
    "dro_base": "DRO Base",
    "f_divergence": "f-Divergence",
    "kl": "KL",
    "kl_dro": "KL-DRO",
    "phi_dro": "Phi-DRO",
    "wasserstein_dro": "Wasserstein DRO",
}
API_NAVIGATION_RE = re.compile(
    r"(?ms)^\s*# BEGIN GENERATED API NAVIGATION\n.*?"
    r"^\s*# END GENERATED API NAVIGATION"
)


@dataclass(frozen=True, slots=True)
class ModuleDoc:
    """Metadata needed to generate one public module reference page."""

    import_path: str
    package_parts: tuple[str, ...]
    name: str
    symbols: tuple[str, ...]

    @property
    def relative_path(self) -> Path:
        """Return the module page path relative to the API docs root."""
        return Path(*self.documentation_parts, f"{self.name}.md")

    @property
    def documentation_parts(self) -> tuple[str, ...]:
        """Return the package path used in the generated documentation tree."""
        return self.package_parts or ("optora",)


def module_symbols(path: Path) -> tuple[str, ...]:
    """Return public classes and functions defined at a module's top level."""
    tree = ast.parse(path.read_text(encoding="utf-8"))
    definitions = (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)
    return tuple(
        node.name
        for node in tree.body
        if isinstance(node, definitions) and not node.name.startswith("_")
    )


def discover_modules(package_root: Path) -> list[ModuleDoc]:
    """Return metadata for public Python modules under ``package_root``."""
    modules: list[ModuleDoc] = []
    for path in package_root.rglob("*.py"):
        if path.name == "__init__.py" or path.name.startswith("_"):
            continue
        relative = path.relative_to(package_root.parent).with_suffix("")
        modules.append(
            ModuleDoc(
                import_path=".".join(relative.parts),
                package_parts=relative.parts[1:-1],
                name=relative.name,
                symbols=module_symbols(path),
            )
        )
    return sorted(modules, key=lambda module: module.import_path)


def display_name(value: str) -> str:
    """Return a human-readable navigation label for a Python name."""
    return DISPLAY_NAMES.get(value, value.replace("_", " ").title())


def render_module_page(module: ModuleDoc) -> str:
    """Render one mkdocstrings page containing a module and its members."""
    return "\n".join(
        [
            GENERATED_NOTICE,
            "",
            f"# `{module.import_path}`",
            "",
            f"::: {module.import_path}",
            "    options:",
            "      members_order: source",
            "      show_root_heading: false",
            "      show_root_toc_entry: false",
            "",
        ]
    )


def render_package_index(
    package_parts: tuple[str, ...], modules: list[ModuleDoc]
) -> str:
    """Render an index linking all modules in one subpackage."""
    package_name = ".".join(("optora", *package_parts))
    sections = [
        GENERATED_NOTICE,
        "",
        f"# `{package_name}`",
        "",
        "## Modules",
    ]
    for module in modules:
        sections.append(f"- [`{module.import_path}`]({module.name}.md)")
        for symbol in module.symbols:
            anchor = f"{module.name}.md#{module.import_path}.{symbol}"
            sections.append(f"    - [`{symbol}`]({anchor})")
    return "\n".join(sections) + "\n"


def group_modules(modules: list[ModuleDoc]) -> dict[tuple[str, ...], list[ModuleDoc]]:
    """Group discovered modules by their owning subpackage."""
    grouped: dict[tuple[str, ...], list[ModuleDoc]] = defaultdict(list)
    for module in modules:
        grouped[module.package_parts].append(module)
    return grouped


def render_api_overview(modules: list[ModuleDoc]) -> str:
    """Render the API landing page as a card grid of subpackages."""
    lines = [
        "---",
        "icon: lucide/book-open",
        "---",
        "",
        GENERATED_NOTICE,
        "",
        "# API reference",
        "",
        "Generated from the source docstrings. Each subpackage lists its",
        "modules, and every module page documents the classes and functions it",
        "defines.",
        "",
        '<div class="grid cards" markdown>',
        "",
    ]
    for package_parts, package_modules in sorted(group_modules(modules).items()):
        package_name = ".".join(("optora", *package_parts))
        package_path = "/".join(package_modules[0].documentation_parts)
        names = ", ".join(f"`{module.name}`" for module in package_modules)
        lines.extend(
            [
                f"-   :material-package-variant:{{ .lg .middle }} __`{package_name}`__",
                "",
                "    ---",
                "",
                f"    {names}",
                "",
                f"    [:octicons-arrow-right-24: Browse]({package_path}/index.md)",
                "",
            ]
        )
    lines.append("</div>")
    return "\n".join(lines) + "\n"


def render_api_navigation(modules: list[ModuleDoc]) -> str:
    """Render hierarchical Zensical navigation for generated API pages."""
    grouped = group_modules(modules)

    lines = ["  # BEGIN GENERATED API NAVIGATION", '  { "API reference" = [']
    lines.append('    { "Overview" = "api/index.md" },')
    for package_parts, package_modules in sorted(grouped.items()):
        documentation_parts = package_modules[0].documentation_parts
        package_path = "/".join(documentation_parts)
        package_label = display_name(package_parts[-1]) if package_parts else "Optora"
        lines.append(f'    {{ "{package_label}" = [')
        lines.append(f'      {{ "Overview" = "api/{package_path}/index.md" }},')
        for module in package_modules:
            path = module.relative_path.as_posix()
            lines.append(f'      {{ "{display_name(module.name)}" = "api/{path}" }},')
        lines.append("    ] },")
    lines.extend(["  ] },", "  # END GENERATED API NAVIGATION"])
    return "\n".join(lines)


def write_if_changed(path: Path, content: str) -> None:
    """Write generated content only when it differs from the existing file."""
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists() or path.read_text(encoding="utf-8") != content:
        path.write_text(content, encoding="utf-8")


def stale_generated_pages(api_root: Path, expected: set[Path]) -> list[Path]:
    """Return obsolete pages owned by this generator."""
    return sorted(
        path
        for path in api_root.rglob("*.md")
        if path not in expected
        and path.read_text(encoding="utf-8").startswith(GENERATED_NOTICE)
    )


def render_documentation(root: Path) -> dict[Path, str]:
    """Render every generator-owned file, including Zensical navigation."""
    modules = discover_modules(root / "optora")
    api_root = root / "docs" / "api"

    pages: dict[Path, str] = {api_root / "index.md": render_api_overview(modules)}
    for package_parts, package_modules in group_modules(modules).items():
        package_root = api_root.joinpath(*package_modules[0].documentation_parts)
        pages[package_root / "index.md"] = render_package_index(
            package_parts, package_modules
        )
        for module in package_modules:
            pages[api_root / module.relative_path] = render_module_page(module)

    config_path = root / "zensical.toml"
    navigation = render_api_navigation(modules)
    updated, count = API_NAVIGATION_RE.subn(
        lambda _: navigation, config_path.read_text(encoding="utf-8")
    )
    if count != 1:
        raise RuntimeError("zensical.toml must contain one generated API nav block")
    pages[config_path] = updated
    return pages


def generate_api_reference(root: Path) -> list[Path]:
    """Generate hierarchical API pages and navigation from the package tree."""
    pages = render_documentation(root)
    for path in stale_generated_pages(root / "docs" / "api", set(pages)):
        path.unlink()
    for path, content in pages.items():
        write_if_changed(path, content)
    return sorted(pages)


def outdated_documentation(root: Path) -> list[Path]:
    """Return generator-owned files that differ from freshly rendered output."""
    pages = render_documentation(root)
    outdated = {
        path
        for path, content in pages.items()
        if not path.exists() or path.read_text(encoding="utf-8") != content
    }
    outdated.update(stale_generated_pages(root / "docs" / "api", set(pages)))
    return sorted(outdated)


def zensical_executable() -> str:
    """Return the Zensical launcher installed beside the active Python."""
    executable_name = "zensical.exe" if sys.platform == "win32" else "zensical"
    executable = Path(sys.executable).with_name(executable_name)
    return str(executable) if executable.exists() else "zensical"


def build_parser() -> argparse.ArgumentParser:
    """Build the documentation command-line parser."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="Repository root. Defaults to this script's parent repository.",
    )
    parser.add_argument(
        "command",
        choices=("generate", "check", "build", "serve"),
        help=(
            "Generate API pages, check them for staleness, build the site, "
            "or serve with live reload."
        ),
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    """Generate API documentation and optionally invoke Zensical."""
    args = build_parser().parse_args(argv)
    root = args.root.resolve()

    if args.command == "check":
        outdated = outdated_documentation(root)
        for path in outdated:
            print(f"Outdated: {path.relative_to(root).as_posix()}")
        if outdated:
            print("Run 'python -m tools.docs generate' and commit the result.")
            return 1
        print("Generated documentation is up to date")
        return 0

    generated = generate_api_reference(root)
    print(f"Generated {len(generated)} documentation files")

    if args.command == "generate":
        return 0

    command = [zensical_executable(), args.command]
    if args.command == "build":
        command.append("--clean")
    return subprocess.run(command, cwd=root, check=False).returncode


if __name__ == "__main__":
    raise SystemExit(main())
