name: Documentation

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          cache: pip
      - uses: actions/configure-pages@v6
        with:
          enablement: ${{ secrets.PAGES_TOKEN != '' }}
          token: ${{ secrets.PAGES_TOKEN || github.token }}
      - run: python -m pip install -U pip
      - run: python -m pip install -e ".[docs]"
      - run: zensical build --clean
      - uses: actions/upload-pages-artifact@v5
        with:
          path: site
      - uses: actions/deploy-pages@v5
        id: deployment
